# Generated by Django 4.0.3 on 2022-05-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auction_object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.TextField()),
                ('purchase', models.IntegerField()),
                ('max_money', models.IntegerField(blank=True, default=0, null=True)),
                ('auction', models.IntegerField()),
                ('term', models.DateField()),
                ('purchase_check', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=66)),
                ('money', models.IntegerField(default=0)),
                ('cookie', models.CharField(blank=True, max_length=1000, null=True)),
                ('max_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchasing_execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction.auction_object')),
                ('purchase_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.user')),
            ],
        ),
        migrations.CreateModel(
            name='auction_participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_purchase', models.IntegerField()),
                ('auction_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction.auction_object')),
                ('auction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.user')),
            ],
        ),
        migrations.AddField(
            model_name='auction_object',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.user'),
        ),
    ]
