# Generated by Django 4.0.3 on 2022-05-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cookie',
            new_name='accessToken',
        ),
    ]
