# Generated by Django 4.0.3 on 2022-05-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_cookie_user_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_object',
            name='Kinds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
